// src/components/CopyButton.vue
<script setup lang="ts">
import { ref } from 'vue'

const props = defineProps<{ text: string; label?: string }>()
const copied = ref(false)
let timer: number | null = null

async function copy() {
  try {
    if (navigator.clipboard && window.isSecureContext) {
      await navigator.clipboard.writeText(props.text)
    } else {
      const ta = document.createElement('textarea')
      ta.value = props.text
      ta.style.position = 'fixed'
      ta.style.opacity = '0'
      document.body.appendChild(ta)
      ta.select()
      document.execCommand('copy')
      document.body.removeChild(ta)
    }
    copied.value = true
    if (timer) window.clearTimeout(timer)
    timer = window.setTimeout(() => (copied.value = false), 1500)
  } catch (e) {
    console.warn('Copy failed', e)
  }
}
</script>

<template>
  <button class="copy-btn" :class="{ copied }" @click="copy" :aria-label="(label || '复制') + '提示词'">
    <span class="dot" aria-hidden="true"></span>
    <span class="label">{{ copied ? '已复制' : (label || '复制') }}</span>
    <span class="check" v-if="copied" aria-hidden="true">✓</span>
  </button>
</template>

<style scoped>
.copy-btn {
  display: inline-flex;
  align-items: center;
  gap: 8px;
  padding: 7px 12px;
  background: rgba(176, 141, 87, 0.08);
  color: var(--c-bronze);
  border: 1px solid var(--c-line-strong);
  border-radius: 2px;
  font-family: var(--f-mono);
  font-size: 11px;
  letter-spacing: 0.12em;
  text-transform: uppercase;
  transition: all var(--t-fast);
  position: relative;
  overflow: hidden;
}
.copy-btn:hover {
  background: rgba(176, 141, 87, 0.18);
  color: var(--c-bronze-glow);
  transform: translateY(-1px);
}
.copy-btn.copied {
  background: rgba(63, 184, 175, 0.18);
  border-color: var(--c-spark);
  color: var(--c-spark-bright);
  transform: scale(1.04);
}
.dot {
  width: 6px;
  height: 6px;
  background: currentColor;
  display: inline-block;
}
.check {
  font-size: 12px;
  font-weight: 700;
}
.label { line-height: 1; }
</style>

// src/components/CopyButton.tsx
import { useState, useCallback } from 'react';
import { Copy, Check } from 'lucide-react';

interface CopyButtonProps {
  text: string;
  label?: string;
}

export default function CopyButton({ text, label = '复制' }: CopyButtonProps) {
  const [copied, setCopied] = useState(false);

  const handleCopy = useCallback(async () => {
    try {
      await navigator.clipboard.writeText(text);
      setCopied(true);
      setTimeout(() => setCopied(false), 2000);
    } catch {
      const ta = document.createElement('textarea');
      ta.value = text;
      ta.style.position = 'fixed';
      ta.style.opacity = '0';
      document.body.appendChild(ta);
      ta.select();
      document.execCommand('copy');
      document.body.removeChild(ta);
      setCopied(true);
      setTimeout(() => setCopied(false), 2000);
    }
  }, [text]);

  return (
    <button
      onClick={handleCopy}
      className={`
        inline-flex items-center gap-2 px-4 py-2 text-sm font-mono-cn
        border transition-all duration-200 cursor-pointer
        ${
          copied
            ? 'bg-[#1a3a6b] text-white border-[#1a3a6b]'
            : 'bg-white text-[#1a1a1a] border-[#1a1a1a] hover:bg-[#1a3a6b] hover:text-white hover:border-[#1a3a6b]'
        }
      `}
    >
      {copied ? <Check size={14} /> : <Copy size={14} />}
      {copied ? '已复制' : label}
    </button>
  );
}
