// src/components/FilterBar.tsx
import { useState } from 'react';
import { ChevronDown, X, Search, SlidersHorizontal } from 'lucide-react';
import { useAppStore } from '../store/useAppStore';
import { WORK_TYPE_LABELS, type WorkType, type Region } from '../data/types';
import { GAME_IPS } from '../data/ips';
import { useMemo } from 'react';

const ALL_TYPES = Object.keys(WORK_TYPE_LABELS) as WorkType[];
const ALL_REGIONS: Region[] = ['Japan', 'USA', 'China', 'Korea', 'Europe', 'Global'];

export default function FilterBar() {
  const types = useAppStore((s) => s.types);
  const regions = useAppStore((s) => s.regions);
  const ipIds = useAppStore((s) => s.ipIds);
  const yearRange = useAppStore((s) => s.yearRange);
  const query = useAppStore((s) => s.query);
  const setQuery = useAppStore((s) => s.setQuery);
  const toggleType = useAppStore((s) => s.toggleType);
  const toggleRegion = useAppStore((s) => s.toggleRegion);
  const toggleIp = useAppStore((s) => s.toggleIp);
  const setYearRange = useAppStore((s) => s.setYearRange);
  const resetFilters = useAppStore((s) => s.resetFilters);
  const [ipQuery, setIpQuery] = useState('');

  const ipList = useMemo(() => {
    const q = ipQuery.trim().toLowerCase();
    if (!q) return GAME_IPS.slice(0, 30);
    return GAME_IPS.filter((g) =>
      g.name.toLowerCase().includes(q) ||
      g.nameEn.toLowerCase().includes(q)
    ).slice(0, 30);
  }, [ipQuery]);

  const hasFilter = types.length || regions.length || ipIds.length || query || yearRange[0] !== 1985 || yearRange[1] !== 2026;

  return (
    <div className="glass rounded-sm p-4 md:p-5 space-y-4 sticky top-20 z-30">
      <div className="flex items-center gap-2 text-neon-cyan font-mono text-xs">
        <SlidersHorizontal className="w-3.5 h-3.5" />
        <span>// FILTERS</span>
        {hasFilter && (
          <button
            onClick={resetFilters}
            className="ml-auto flex items-center gap-1 text-white/40 hover:text-neon-pink text-[10px] tracking-widest"
          >
            <X className="w-3 h-3" /> RESET
          </button>
        )}
      </div>

      {/* 搜索 */}
      <div className="relative">
        <Search className="absolute left-3 top-1/2 -translate-y-1/2 w-4 h-4 text-neon-cyan" />
        <input
          value={query}
          onChange={(e) => setQuery(e.target.value)}
          placeholder="搜索作品名 / IP / 标签..."
          className="w-full bg-ink-700/60 border border-white/10 focus:border-neon-cyan/60 focus:shadow-neon-cyan outline-none pl-10 pr-3 py-2 text-sm rounded-sm font-mono placeholder:text-white/30 transition"
        />
      </div>

      {/* 类型 */}
      <div>
        <Label>类型</Label>
        <div className="flex flex-wrap gap-1.5">
          {ALL_TYPES.map((t) => {
            const on = types.includes(t);
            return (
              <button
                key={t}
                onClick={() => toggleType(t)}
                className={`text-xs px-2.5 py-1 rounded-sm border transition ${
                  on
                    ? 'border-neon-pink bg-neon-pink/10 text-neon-pink shadow-neon-pink'
                    : 'border-white/10 text-white/60 hover:border-neon-cyan/40 hover:text-neon-cyan'
                }`}
              >
                {WORK_TYPE_LABELS[t]}
              </button>
            );
          })}
        </div>
      </div>

      {/* 地区 */}
      <div>
        <Label>地区</Label>
        <div className="flex flex-wrap gap-1.5">
          {ALL_REGIONS.map((r) => {
            const on = regions.includes(r);
            return (
              <button
                key={r}
                onClick={() => toggleRegion(r)}
                className={`text-xs px-2.5 py-1 rounded-sm border transition ${
                  on
                    ? 'border-neon-cyan bg-neon-cyan/10 text-neon-cyan shadow-neon-cyan'
                    : 'border-white/10 text-white/60 hover:border-neon-cyan/40 hover:text-neon-cyan'
                }`}
              >
                {r}
              </button>
            );
          })}
        </div>
      </div>

      {/* IP 下拉 */}
      <details className="group">
        <summary className="flex items-center justify-between cursor-pointer text-white/80 text-xs font-mono py-1 list-none">
          <span className="flex items-center gap-2">
            <span>// 选择 IP</span>
            {ipIds.length > 0 && (
              <span className="text-neon-yellow">({ipIds.length})</span>
            )}
          </span>
          <ChevronDown className="w-3.5 h-3.5 group-open:rotate-180 transition" />
        </summary>
        <div className="mt-2 space-y-2">
          <input
            value={ipQuery}
            onChange={(e) => setIpQuery(e.target.value)}
            placeholder="搜索 IP 名..."
            className="w-full bg-ink-700/40 border border-white/10 outline-none px-2.5 py-1.5 text-xs rounded-sm font-mono placeholder:text-white/30"
          />
          <div className="max-h-56 overflow-y-auto pr-1 space-y-1">
            {ipList.map((ip) => {
              const on = ipIds.includes(ip.id);
              return (
                <button
                  key={ip.id}
                  onClick={() => toggleIp(ip.id)}
                  className={`w-full flex items-center gap-2 px-2 py-1.5 rounded-sm text-xs text-left transition ${
                    on
                      ? 'bg-neon-violet/15 text-neon-violet border border-neon-violet/30'
                      : 'hover:bg-white/5 text-white/70 border border-transparent'
                  }`}
                >
                  <span
                    className="w-2 h-2 rounded-full shrink-0"
                    style={{ background: ip.color }}
                  />
                  <span className="truncate flex-1">{ip.name}</span>
                  <span className="text-[10px] text-white/30 font-mono">{ip.region}</span>
                </button>
              );
            })}
            {ipList.length === 0 && (
              <div className="text-center text-white/30 text-xs py-3">未找到匹配 IP</div>
            )}
          </div>
        </div>
      </details>

      {/* 年份 */}
      <div>
        <Label>年份 {yearRange[0]} - {yearRange[1]}</Label>
        <div className="grid grid-cols-2 gap-2">
          <NumberInput
            value={yearRange[0]}
            min={1985}
            max={yearRange[1]}
            onChange={(v) => setYearRange([v, yearRange[1]])}
          />
          <NumberInput
            value={yearRange[1]}
            min={yearRange[0]}
            max={2026}
            onChange={(v) => setYearRange([yearRange[0], v])}
          />
        </div>
        <input
          type="range"
          min={1985}
          max={2026}
          value={yearRange[1]}
          onChange={(e) => setYearRange([yearRange[0], Number(e.target.value)])}
          className="w-full mt-2 accent-neon-cyan"
        />
      </div>
    </div>
  );
}

function Label({ children }: { children: React.ReactNode }) {
  return (
    <div className="text-[10px] text-white/40 font-mono tracking-widest mb-1.5">
      {children}
    </div>
  );
}

function NumberInput({ value, min, max, onChange }: { value: number; min: number; max: number; onChange: (v: number) => void }) {
  return (
    <input
      type="number"
      value={value}
      min={min}
      max={max}
      onChange={(e) => {
        const v = Number(e.target.value);
        if (!Number.isNaN(v)) onChange(Math.max(min, Math.min(max, v)));
      }}
      className="w-full bg-ink-700/40 border border-white/10 outline-none px-2 py-1.5 text-xs font-mono rounded-sm"
    />
  );
}

// src/components/FilterBar.vue
<script setup lang="ts">
import { ref, computed, watch } from 'vue';
import { ChevronDown, X, Search, SlidersHorizontal } from 'lucide-vue-next';
import { useAppStore } from '@/stores/app';
import { WORK_TYPE_LABELS, WORK_TYPE_LIST, REGION_LIST } from '@/data/types';
import type { WorkType, Region } from '@/data/types';
import { GAME_IPS } from '@/data/ips';

const store = useAppStore();
const ipQuery = ref('');

const ipList = computed(() => {
  const q = ipQuery.value.trim().toLowerCase();
  if (!q) return GAME_IPS.slice(0, 30);
  return GAME_IPS.filter(
    (g) => g.name.toLowerCase().includes(q) || g.nameEn.toLowerCase().includes(q)
  ).slice(0, 30);
});

const hasFilter = computed(() => store.activeFilterCount > 0);
</script>

<template>
  <div class="glass rounded-sm p-4 md:p-5 space-y-4 sticky top-20 z-30">
    <div class="flex items-center gap-2 text-neon-cyan font-mono text-xs">
      <SlidersHorizontal class="w-3.5 h-3.5" />
      <span>// FILTERS</span>
      <span v-if="hasFilter" class="text-neon-yellow">[{{ store.activeFilterCount }}]</span>
      <button
        v-if="hasFilter"
        @click="store.resetFilters()"
        class="ml-auto flex items-center gap-1 text-white/40 hover:text-neon-pink text-[10px] tracking-widest"
      >
        <X class="w-3 h-3" /> RESET
      </button>
    </div>

    <div class="relative">
      <Search class="absolute left-3 top-1/2 -translate-y-1/2 w-4 h-4 text-neon-cyan" />
      <input
        :value="store.query"
        @input="(e) => store.setQuery((e.target as HTMLInputElement).value)"
        placeholder="搜索作品名 / IP / 标签..."
        class="w-full bg-ink-700/60 border border-white/10 focus:border-neon-cyan/60 focus:shadow-neon-cyan outline-none pl-10 pr-3 py-2 text-sm rounded-sm font-mono placeholder:text-white/30 transition"
      />
    </div>

    <div>
      <div class="text-[10px] text-white/40 font-mono tracking-widest mb-1.5">类型</div>
      <div class="flex flex-wrap gap-1.5">
        <button
          v-for="t in WORK_TYPE_LIST"
          :key="t"
          @click="store.toggleType(t as WorkType)"
          :class="[
            'text-xs px-2.5 py-1 rounded-sm border transition',
            store.types.includes(t as WorkType)
              ? 'border-neon-pink bg-neon-pink/10 text-neon-pink shadow-neon-pink'
              : 'border-white/10 text-white/60 hover:border-neon-cyan/40 hover:text-neon-cyan'
          ]"
        >
          {{ WORK_TYPE_LABELS[t as WorkType] }}
        </button>
      </div>
    </div>

    <div>
      <div class="text-[10px] text-white/40 font-mono tracking-widest mb-1.5">地区</div>
      <div class="flex flex-wrap gap-1.5">
        <button
          v-for="r in REGION_LIST"
          :key="r"
          @click="store.toggleRegion(r as Region)"
          :class="[
            'text-xs px-2.5 py-1 rounded-sm border transition',
            store.regions.includes(r as Region)
              ? 'border-neon-cyan bg-neon-cyan/10 text-neon-cyan shadow-neon-cyan'
              : 'border-white/10 text-white/60 hover:border-neon-cyan/40 hover:text-neon-cyan'
          ]"
        >
          {{ r }}
        </button>
      </div>
    </div>

    <details class="group">
      <summary class="flex items-center justify-between cursor-pointer text-white/80 text-xs font-mono py-1 list-none">
        <span class="flex items-center gap-2">
          <span>// 选择 IP</span>
          <span v-if="store.ipIds.length" class="text-neon-yellow">({{ store.ipIds.length }})</span>
        </span>
        <ChevronDown class="w-3.5 h-3.5 group-open:rotate-180 transition" />
      </summary>
      <div class="mt-2 space-y-2">
        <input
          v-model="ipQuery"
          placeholder="搜索 IP 名..."
          class="w-full bg-ink-700/40 border border-white/10 outline-none px-2.5 py-1.5 text-xs rounded-sm font-mono placeholder:text-white/30"
        />
        <div class="max-h-56 overflow-y-auto pr-1 space-y-1">
          <button
            v-for="ip in ipList"
            :key="ip.id"
            @click="store.toggleIp(ip.id)"
            :class="[
              'w-full flex items-center gap-2 px-2 py-1.5 rounded-sm text-xs text-left transition',
              store.ipIds.includes(ip.id)
                ? 'bg-neon-violet/15 text-neon-violet border border-neon-violet/30'
                : 'hover:bg-white/5 text-white/70 border border-transparent'
            ]"
          >
            <span class="w-2 h-2 rounded-full shrink-0" :style="{ background: ip.color }" />
            <span class="truncate flex-1">{{ ip.name }}</span>
            <span class="text-[10px] text-white/30 font-mono">{{ ip.region }}</span>
          </button>
        </div>
      </div>
    </details>

    <div>
      <div class="text-[10px] text-white/40 font-mono tracking-widest mb-1.5">
        年份 {{ store.yearRange[0] }} - {{ store.yearRange[1] }}
      </div>
      <div class="grid grid-cols-2 gap-2">
        <input
          type="number"
          :value="store.yearRange[0]"
          min="1985"
          :max="store.yearRange[1]"
          @change="(e) => store.setYearRange([Number((e.target as HTMLInputElement).value), store.yearRange[1]])"
          class="w-full bg-ink-700/40 border border-white/10 outline-none px-2 py-1.5 text-xs font-mono rounded-sm"
        />
        <input
          type="number"
          :value="store.yearRange[1]"
          :min="store.yearRange[0]"
          max="2026"
          @change="(e) => store.setYearRange([store.yearRange[0], Number((e.target as HTMLInputElement).value)])"
          class="w-full bg-ink-700/40 border border-white/10 outline-none px-2 py-1.5 text-xs font-mono rounded-sm"
        />
      </div>
      <input
        type="range"
        min="1985"
        max="2026"
        :value="store.yearRange[1]"
        @input="(e) => store.setYearRange([store.yearRange[0], Number((e.target as HTMLInputElement).value)])"
        class="w-full mt-2 accent-neon-cyan"
      />
    </div>
  </div>
</template>
