// src/components/Hero.vue
<script setup lang="ts">
import { Sparkles, Cpu, ArrowDown } from 'lucide-vue-next';
import { RouterLink } from 'vue-router';
import Counter from './Counter.vue';
import { TOTAL_WORKS } from '@/data/works';
</script>

<template>
  <section class="relative pt-16 pb-24 overflow-hidden">
    <div class="absolute inset-0 bg-radial-fade" />
    <div class="absolute inset-0 bg-grid opacity-50" />
    <div class="absolute inset-0 noise" />

    <div class="absolute -top-32 -left-32 w-96 h-96 bg-neon-pink/20 rounded-full blur-3xl" />
    <div class="absolute top-32 -right-32 w-96 h-96 bg-neon-cyan/20 rounded-full blur-3xl" />
    <div class="absolute bottom-0 left-1/2 -translate-x-1/2 w-[800px] h-[300px] bg-neon-violet/10 rounded-full blur-3xl" />

    <div class="container relative">
      <div class="flex flex-col items-center text-center max-w-5xl mx-auto">
        <div class="inline-flex items-center gap-2 px-3 py-1 mb-6 border border-neon-cyan/40 bg-neon-cyan/5 rounded-sm">
          <span class="w-1.5 h-1.5 bg-neon-cyan rounded-full animate-pulse" />
          <span class="font-mono text-[10px] tracking-widest text-neon-cyan">
            DATABASE_v3.0 // RELEASED 2026-06-08 // VUE_3
          </span>
        </div>

        <h1 class="font-display text-5xl md:text-7xl lg:text-8xl font-black leading-[0.95] tracking-tight">
          <span class="block text-glow text-neon-cyan">GAME IP</span>
          <span class="block mt-1 text-gradient-neon">DERIVATIVES</span>
          <span class="block mt-1 text-white/90 text-3xl md:text-4xl lg:text-5xl">
            衍生作品 <span class="text-neon-pink">资料库</span>
          </span>
        </h1>

        <p class="mt-6 max-w-2xl text-base md:text-lg text-white/60 leading-relaxed">
          面向 <span class="text-neon-cyan font-medium">10 万级</span> 企业级规模，
          全球首个开源、现代化的 <span class="text-neon-cyan font-medium">游戏 IP 衍生作品</span> 浏览平台。
          覆盖动画、漫画、电影、小说、舞台剧、手办、周边、音乐、真人剧等
          <span class="text-neon-pink font-medium"> {{ TOTAL_WORKS.toLocaleString() }}+ </span>
          款真实条目，<span class="text-neon-violet font-medium">355+ </span> 个 IP。
        </p>

        <div class="mt-10 grid grid-cols-3 gap-4 md:gap-12">
          <div class="flex flex-col items-center">
            <div class="font-display text-3xl md:text-5xl font-black text-neon-pink">
              <Counter :end="TOTAL_WORKS" />
              <span class="text-white/40 text-2xl md:text-3xl">+</span>
            </div>
            <div class="mt-1 font-mono text-[10px] md:text-xs text-white/40 tracking-widest">DERIVATIVES</div>
          </div>
          <div class="flex flex-col items-center">
            <div class="font-display text-3xl md:text-5xl font-black text-neon-cyan">
              <Counter :end="355" />
              <span class="text-white/40 text-2xl md:text-3xl">+</span>
            </div>
            <div class="mt-1 font-mono text-[10px] md:text-xs text-white/40 tracking-widest">GAME_IPS</div>
          </div>
          <div class="flex flex-col items-center">
            <div class="font-display text-3xl md:text-5xl font-black text-neon-violet">
              <Counter :end="100" />
              <span class="text-white/40 text-2xl md:text-3xl">K+</span>
            </div>
            <div class="mt-1 font-mono text-[10px] md:text-xs text-white/40 tracking-widest">SCALE_TARGET</div>
          </div>
        </div>

        <div class="mt-10 flex flex-wrap items-center justify-center gap-4">
          <RouterLink to="/browse" class="btn-neon group">
            <Sparkles class="w-4 h-4 group-hover:rotate-12 transition" />
            开始浏览
          </RouterLink>
          <RouterLink to="/dashboard" class="btn-neon btn-pink group">
            <Cpu class="w-4 h-4 group-hover:scale-110 transition" />
            数据看板
          </RouterLink>
          <a href="#stats" class="flex items-center gap-1 text-sm text-white/50 hover:text-white transition">
            <span class="font-mono">// 向下滚动</span>
            <ArrowDown class="w-3.5 h-3.5 animate-bounce" />
          </a>
        </div>
      </div>
    </div>
  </section>
</template>

// ai-creation-gallery/src/components/home/Hero.tsx
import { Link } from "react-router-dom";
import { ArrowRight, Images, Mountain, Sparkle, ChevronDown } from "lucide-react";
import { stats } from "@/data/meta";
import { useCountUp } from "@/hooks/useCountUp";
import StatsStrip from "./StatsStrip";

export default function Hero() {
  return (
    <section className="relative overflow-hidden">
      {/* floating orbs */}
      <div className="pointer-events-none absolute inset-0 -z-10">
        <div className="absolute left-[8%] top-[12%] h-72 w-72 rounded-full bg-magenta/20 blur-3xl animate-floatY" />
        <div className="absolute right-[10%] top-[22%] h-80 w-80 rounded-full bg-cyan/15 blur-3xl animate-floatY2" />
        <div className="absolute bottom-[6%] left-[40%] h-72 w-72 rounded-full bg-rarity-epic/15 blur-3xl animate-floatY" />
        <div
          className="absolute inset-0 opacity-[0.4] bg-grid-faint"
          style={{ backgroundSize: "44px 44px", maskImage: "radial-gradient(circle at 50% 40%, #000, transparent 75%)" }}
        />
      </div>

      <div className="container relative flex min-h-[88vh] flex-col justify-center py-24">
        <div className="max-w-3xl animate-fadeUp">
          <div className="section-eyebrow">
            <Sparkle size={13} className="text-magenta" />
            抖音热门 · AI 二创聚合策展
          </div>

          <h1 className="font-display text-5xl font-black leading-[0.95] tracking-tight text-white sm:text-6xl md:text-7xl lg:text-8xl">
            CYBER
            <br />
            <span className="text-gradient neon-text">CURATORIUM</span>
          </h1>

          <p className="mt-6 max-w-xl text-base leading-relaxed text-white/60 sm:text-lg">
            将散落于短视频平台的 AI 二创精品，按
            <span className="mx-1 text-magenta-soft">角色卡牌</span>·
            <span className="mx-1 text-cyan-soft">场景壁纸</span>·
            <span className="mx-1 text-rarity-legendary">物品设计</span>
            三大维度系统化聚合，打造你的 AI 创作灵感中枢。
          </p>

          <div className="mt-9 flex flex-wrap items-center gap-4">
            <Link to="/cards" className="btn-primary">
              <Images size={18} /> 探索馆藏
              <ArrowRight size={16} />
            </Link>
            <Link to="/scenes" className="btn-ghost">
              <Mountain size={18} /> 热门场景
            </Link>
          </div>
        </div>

        <StatsStrip />

        <div className="mt-16 flex items-center gap-2 text-xs font-mono text-white/30 animate-glowPulse">
          <ChevronDown size={14} className="animate-bounce" />
          SCROLL TO EXPLORE
        </div>
      </div>
    </section>
  );
}
